### PR TITLE
Css refactor

### PR DESCRIPTION
**Pull request by Pineapple69**

### CODE REVIEW

**Comment by DuongTyler** [comment]
There is an issue with the CSS not correctly centering the cards when the width of the screen is >1800px
image

**Comment by DuongTyler** [comment]
additionally, the borders for the cards don't get any side padding until we zoom in to something like 1400px

**Comment by DuongTyler** [comment]
Games section is affected by visiting the homepage:

BEFORE HOMEPAGE:
image

AFTER HOMEPAGE:
image

**Review by DuongTyler — APPROVED** [review]
everything looks ok to me so far.

**Review by zapplecat — COMMENTED** [review]
Slowly getting through this. I'll finish by the end of today.

**Comment by zapplecat** [comment]
I can't find where, but I thought the message card didn't used to show overflow scrollers

image

**Review by zapplecat — APPROVED** [review]
Just the issue I mentioned with the scrollbar, along with some nit picks. Otherwise, everything else looks good. お疲れ。

**Pull request merged**
