### PR TITLE
Highlight current page icon

### PR DESCRIPTION
**Pull request by zapplecat**
Addressing #149 and highlighting the icon of the current page the user is on.

### CODE REVIEW

**Comment by DuongTyler** [comment]
I love the way everything looks, but the information tab still remains highlighted no matter what. Are we able to darken that info tab permanently?

**Comment by zapplecat** [comment]
> I love the way everything looks, but the information tab still remains highlighted no matter what. Are we able to darken that info tab permanently?

Done :)

**Comment by DuongTyler** [comment]
Looks good to me, but I'll let someone with a bit more experience look through this.

**Review by kuroni — APPROVED** [review]
Looks good to me

**Pull request merged**
